---
- name: Downloading easy rsa
  get_url:
    url: "{{ easy_rsa_url }}"
    dest: /tmp/
    validate_certs: False

- name: Unarchiving easy-rsa
  unarchive:
    src: /tmp/EasyRSA-3.0.4.tgz
    dest: /tmp
    creates: /tmp/{{ easy_rsa_pkg }}
    remote_src: true

- name: Creating easy-rsa directory in openvpn directory
  file:
    path: etc/openvpn/easy-rsa
    state: directory

- name: Copying rsa files to the working directory
  shell: cp -R /tmp/{[ easy_rsa_pkg }} /{{ base_directory }}/easy-rsa
  args:
    creates: /{{ base_directory }}/easy-rsa
...